#!/bin/bash

. ${GP_LIB:=/usr/share/gitpkg}/gp_common

if [[ -d $pkg_dir ]]; then
    case $1 in 
	--* )
	    exec gp_release "$@" ;;
	"" )
	    echo "What should I do?" ;;
	* )
	    cd $pkg_dir
	    exec git "$@" ;;
    esac
else
    case $1 in 
	--* )
	    exec gp_setup "$@" ;;
	"" ) # If there's a packaging branch - typically used post git clone
	    if git_branch_exists $pkg_branch; then
		ensure_rpm_subdir $pkg_branch
	    fi;;
    esac
fi
