# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       gitpkg

# >> macros
# << macros

Summary:    Helps manage packaging in git
Version:    0.0.1
Release:    1
Group:      Development
License:    GPLv2
Source0:    gitpkg-0.0.1.tar.bz2
Source100:  gitpkg.yaml
Requires:   git
Requires:   pristine-tar
Requires:   python

%description
Allows the packaging to be maintained in a discrete git tree in the same git repo as the source


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
# << files
