#!/bin/bash

# gp_release
# This is part of the Mer git-packaging suite

. ${GP_LIB:=/usr/share/gitpkg}/gp_common

assert_not_on_pkg_branch() {
    if [[ $initial_branch == "pkg-$DISTRO" ]]; then
	cat <<EOF
$ME must not be run from the pkg-$DISTRO branch. Maybe
git checkout -f master

EOF
	exit 1
    fi
}

git_tag_exists() { git show-ref --tags --quiet --verify -- "refs/tags/$1"; }
git_branch_exists() { git show-ref --quiet --verify -- "refs/heads/$1"; }

switch_to_pkg(){
    git checkout -f pkg-$DISTRO || { fatal "Can't checkout pkg-$DISTRO, aborting"; }
}

cleanup(){
    # switch back to initial branch
    echo "Attempting to switch back to $initial_branch in git"
    git checkout $initial_branch
}

update_changes(){ # release oldpatchtag patchtag
    release=$1
    tag1=$2
    tag2=$3
    changes=$(find . -maxdepth 1 -name '*changes' -print -quit)
    newchanges=$(mktemp changes_XXXXX)
    date +"* %a %b %Y ${GIT_AUTHOR_NAME:-Your Name (Set \$GIT_AUTHOR_NAME)} <${GIT_AUTHOR_EMAIL:-Your Email Set \$GIT_AUTHOR_EMAIL}> - $release" > $newchanges
    cat <<EOF >> $newchanges
- Please enter a changelog message

#### Relevant gitlog. This line and lines up to the next changelog entry will be removed.
EOF
    git log $tag1..$tag2  >> $newchanges
    echo "#### this line will be removed" >> $newchanges
    cat *.changes >> $newchanges
    $EDITOR $newchanges
    sed -i '/^### Relevant gitlog/,/^### this line will/d' $newchanges
    mv $newchanges $changes || exit 1
}

usage() {
    cat <<EOF
    $ME [--ver[=<version-release>]] [--base=<tag>] [--edit]
 
       Used to create a new release or prepare for an intermediate
       build

       --ver[=<version-release>]

         if --ver is used then a new package version will be created.
         Updates to _src, .changes, .yaml and .spec files are
         made. Version: / Release: values and Patches: lines will be
         updated in the yaml/spec. A changelog entry is prompted for
         (using git log as a base) and the git repo will be tagged.

         If <version-release> is not specified then it is guessed from
         the packaging and uses perls string increment on
         <release>. This often works :)

         HEAD when the command is run will be tagged as
         $DISTRO-<version-release> and packaging as
         pkg-$DISTRO-<version-release>. (Usually git checkout -f
         master would be run before running $ME)

       --base=<tag>

         If --base is provided then it is used as the new base tag
         from which patches are based. If --ver=<version>-<release> is
         not given then <version> is assumed to be <tag> and <release>
         is assumed to be "1". A $DISTRO-master branch will be made
         if not present.

       --edit

         If --edit is provided then the final commit/tag step on the
         packaging branch is not made so that the spec/yaml can be
         edited manually. The commit/tag commands are printed for
         reference.

       If --ver is not given then the packaging branch pkg-$DISTRO is
       checked out, the spec/yaml is updated by appending
       .gitcount.sha1 to the Release: value (this tries to ensure rpm
       release values increment in a manner that allow rpm upgrades to
       work).
       ADDITIONALLY: a normal gp_mkpkg is used to prepare the tarball
       and patches when --ver is not given.

       --git-dir=<dir>
         The --git-dir option is ideal for working with a local OBS
         checkout and doing local OBS builds. It makes most sense when
         --ver is not specified
         Internally it sets GIT_DIR to <dir> and GIT_WORK_TREE to cwd

       $DISTRO is set either in ~/.gitpkg, the GITPKG_DISTRO
       environment variable or using --distro=<DISTRO>. If not
       specified 'mer' is used.

EOF
}

do_release() {
    verrel_regex="^[^-]+-[^-]+$"
    #  or  "^[a-zA-Z0-9.~_]+-[a-zA-Z0-9.~_]+$" ?

    while [[ $1 ]]; do
	case $1 in
	    --base=*)
		newbase=${1#*=}
		if not git_tag_exists $newbase; then
		    fatal "--base must provide a valid tag. '$newbase' is not a valid tag."
		fi
		# if a plain --ver is given aswell (ie without
		# =ver-rel) that's ambiguous since --base implies a
		# new version
		# so override to 'basetag' and we'll set ver=$newbase and rel=1
		get_verrel=newbase
		shift;;
	    --ver )
		# Now if --base was given, don't override from packaging
		get_verrel=${get_verrel:-packaging}
		shift;;
	    --ver=* )
		verrel=${1#*=}
		if [[ $verrel =~ $verrel_regex ]]; then
		    ver=${verrel%-*}
		    rel=${verrel##*-}
		else
		    fatal "The --ver= option must provide <ver>-<rel>"
		fi
		# if $verrel is "" then we guess it later when the packaging is present
		shift ;;
	    --edit )
		manual_edit=true
		shift ;;
	    --git-dir=*)
		gitdir=${1#*=}
		if ! git  --git-dir $gitdir rev-parse --git-dir > /dev/null 2>&1; then
		    # not a git dir - try appending .git
		    if git --git-dir $gitdir/.git rev-parse --git-dir > /dev/null 2>&1; then
			gitdir=$gitdir/.git
		    else
			fatal "The --git-dir option must point to a git repo. \n" \
                            "$gitdir nor $gitdir/.git are a git directory"
		    fi
		fi
		export GIT_WORK_TREE=$(pwd)
		export GIT_DIR=$gitdir
		export GIT_INDEX_FILE=$(mktemp /tmp/gp.index_XXXXX)
		git read-tree --empty
		shift ;;
	    *-h*) usage;
		exit 0;;
	    * )
		echo "Error $1 not recognised"
		usage
		exit 1;;
	esac
    done

    git rev-parse --git-dir > /dev/null 2>&1 || 
	fatal "This is not a git repository; use $ME in a gitpkg git repo or use --git-dir."

    # We need a clean tree unless we're in another directory using --git-dir
    if ! [[ $GIT_INDEX_FILE ]]; then require_clean_work_tree "run $ME"; fi

    save_initial_branch
    assert_not_on_pkg_branch

    # store current git postion
    patchtag_sha1=$(git rev-parse HEAD)
    
    trap cleanup EXIT
    switch_to_pkg

    # Get ver-rel and increment it if we need to
    case $get_verrel in
	packaging )
	    get_verrel_from_packaging .
	    oldrel=$rel
	    rel=$(perl -e"\$r='$rel';print ++\$r;")
	    echo "Automagically guessed $ver-$oldrel -> $ver-$rel"
	    verrel=$ver-$rel
	    if ! [[ $rel ]] || [[ $rel == "1" ]]; then
		fatal "The value guessed for Release: is '$rel' and this is probably wrong.\n" \
                    "Please specify an exact value for --ver=\n" \
		    "Currently Version: $ver and Release: $oldrel"
	    fi
	    ;;
	newbase )
	    # if we have a newbase and no ver/rel then set them:
	    if ! [[ $verrel ]]; then
		ver=$newbase
		rel=1
	    fi
	    ;;
    esac

    # Update _src
    IFS=: read type tarball basetag oldpatchtag rest < _src

    if [[ $verrel ]]; then
	patchtag=${DISTRO}-$verrel
    else
	patchtag=$patchtag_sha1
    fi

    # If we have a new basetag ...
    if [[ $newbase ]]; then
	basetag=$newbase
	# The mer-master branch should point here now
	echo "Reset $DISTRO-master branch to start at $basetag"
	git branch -f $DISTRO-master $basetag
    fi

    # if basetag and patchtag have the same sha1...
    if [[ $(git rev-parse $basetag) == $(git rev-parse $patchtag) ]]; then
	echo ${type}:${tarball}:${basetag} > _src
    else
	echo ${type}:${tarball}:${basetag}:${patchtag} > _src
    fi

    # Update the yaml or spec (or abort)
    pkgfile=$(find . -maxdepth 1 -name '*yaml' -print -quit)
    if [[ ! $pkgfile ]]; then
	pkgfile=$(find . -maxdepth 1 -name '*spec' -print -quit)
    fi
    if [[ ! $pkgfile ]]; then
	fatal "No spec or yaml files found"
    fi

    if [[ $verrel ]]; then
	sed -i -e"s/Version:.*/Version: $ver/" $pkgfile
	sed -i -e"s/Release:.*/Release: $rel/" $pkgfile
	update_changes $verrel $oldpatchtag $patchtag_sha1
        # We need to tag source before running gp_mkpkg
	git tag $patchtag $patchtag_sha1

        # All done, use gp_mkpkg to update patch lists in yaml/spec etc
	gp_mkpkg --no-tarball --no-checkout

        # and commit
	if [[ $manual_edit ]]; then
	    git add -u .
	    cat <<EOF

The packaging has been prepared. You may now manally edit the
packaging.

When you are done, commit and tag the changes:

git commit -am"Release $patchtag"
git tag pkg-$patchtag
EOF
	    # Don't try to switch back to original branch
	    trap - EXIT
	else
	    git commit -am"Release $patchtag"
	    git tag pkg-$patchtag
	fi
    else
	sha1=$(git rev-parse --short $patchtag_sha1)
	gitcount=$(count_commits ${basetag} ${patchtag})
	sed -i -re"s/Release:\s*(\S*)/Release: \1.$gitcount.$sha1/" $pkgfile
	# Now add a dummy changelog entry
	changes=$(find . -maxdepth 1 -name '*changes' -print -quit)
	newchanges=$(mktemp changes_XXXXX)
	date +"* %a %b %Y ${GIT_AUTHOR_NAME:-Your Name (Set \$GIT_AUTHOR_NAME)} <${GIT_AUTHOR_EMAIL:-Your Email Set \$GIT_AUTHOR_EMAIL}> - $release" > $newchanges
	echo -e "- git commits from $oldpatchtag to $sha1" >> $newchanges
	git log ${oldpatchtag}..$patchtag_sha1 --oneline | sed -e 's/^/   /' >> $newchanges
	echo >> $newchanges
	cat *.changes >> $newchanges
	mv $newchanges $changes || exit 1

        # All done, use gp_mkpkg to update patch lists in yaml/spec etc
	gp_mkpkg --no-checkout

	cat <<EOF
The tarball and patches have been prepared for building.
EOF
	# Don't try to switch back to original branch
	trap - EXIT
    fi
}

do_release $*
