#!/bin/bash

# gp_setup
# This is part of the Mer git-packaging suite
# It sets up a git repo to use git-pkg

# If not
# Check if a mer-pkg exists already
# Create mer-pkg
# Add templates

DISTRO=mer
pkg_branch=pkg-$DISTRO

[[ -d .git ]] || {
    echo "This is not a git repository; use gp_setup when you've cloned or created a normal src repo that is ready for packaging".
    exit 1
}

usage() {
    cat <<EOF
    gp_setup --pkg [--distro=<DISTRO>]
    gp_setup --existing --base-on=<tag>|--unpack=<tag> \
             --pkgdir=<packaging dir> \
             [--patch-branch=<branch/tag>]  [--pristine] \
             [--distro=<DISTRO>]
 
       Used to setup an existing git repo for git-pkg

       $DISTRO is set either in ~/.gitpkg, the GITPKG_DISTRO
       environment variable or using --distro=<DISTRO>. If not
       specified 'mer' is used.

EOF
    # keep the usage msg near the code:
    usage_pkg
    usage_existing
}

count_commits() {
    git rev-list $1..$2 | wc -l
}

# http://stackoverflow.com/a/3879077/337649
require_clean_work_tree() {
    # Update the index
    git update-index -q --ignore-submodules --refresh
    err=0

    # Disallow unstaged changes in the working tree
    if ! git diff-files --quiet --ignore-submodules --
    then
        echo >&2 "cannot $1: you have unstaged changes."
        git diff-files --name-status -r --ignore-submodules -- >&2
        err=1
    fi

    # Disallow uncommitted changes in the index
    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
    then
        echo >&2 "cannot $1: your index contains uncommitted changes."
        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
        err=1
    fi

    if [ $err = 1 ]
    then
        echo >&2 "Please commit or stash them before using gp_setup."
        exit 1
    fi
}

unpack_tarball() {
    rm -rf *
    tar --transform 's_[^/]*/__' -xf $1
}

usage_existing() {
get_verrel_from_packaging() {
    # See if there's a yaml or a .spec
    vrfile=$(cd $pkgdir; find . -maxdepth 1 -name '*yaml' -print -quit)
    vrfile=${vrfile:-$(cd $pkgdir; find . -maxdepth 1 -name '*spec' -print -quit)}
    if [[ -f $pkgdir/$vrfile ]]; then
	ver=$(grep Version: $pkgdir/$vrfile | cut -f2 -d: | tr -d ' ')
	rel=$(grep Release: $pkgdir/$vrfile | cut -f2 -d: | tr -d ' ')
    fi
}

cat <<EOF
    --existing [--pristine] --base-on=<tag>|--unpack=<tag>
                --pkgdir=<packaging dir> [--patch-branch=<branch/tag>]
               [--ver=<ver>[-<rel>]]

       Takes an existing set of packaging and applies it to some git repo.
       This can be used in 3 ways:
         1) with an upstream git and some packaging/patches
         2) with an upstream tarball and some packaging/patches
         3) with an upstream git, an upstream tarball and some packaging/patches
            (eg where upstream does some post-processing after a git
            checkout)

       --base-on=<basetag>
                   The existing tag to base the packaging on.
                   Typically the upstream release tag.

                   If --pristine is used then it looks in <packaging
                   dir> for a tarball and uses that as the basis for
                   the build.

       --unpack-to=<basetag>
                  Uses an empty git (implies --pristine); looks in
                  <packaging dir> for a tarball and uses that as the
                  basis for the build.  Unpacks the tarball as an
                  initial commit and applies the given tag to the
                  unpacked tarball

       --ver=<ver>[-<rel>]
                  If the upstream <basetag> is not the X.Y.Z version
                  then specify the version and optionally the release.
                  (Could come from spec/.changes?)

       --pkgdir=<packaging dir>
                  is the source dir for the spec/yaml/changes/patches
                  This could be a 'checked out' osc dir.
                  Any patches found in pkgdir are applied at <tag>
EOF
}

use_existing() {

    gp_type="git"
    unpack=
    FUZZ="--fuzz=2"
    # better option parsing welcomed

    while [[ $1 ]]; do
	case $1 in
	    --pristine )
		gp_type="pristine-tar"
		shift ;;
	    --base-on* )
		basetag=${1#*=}
		# if tag is empty, complain
		shift ;;
	    --unpack-to=* )
		# Would be nice to default to tag=version
		unpack=true
		basetag=${1#*=}
		shift ;;
	    --pkgdir=* )
		pkgdir=${1#*=}
		shift ;;
	    --ver=* )
		# Would be nice to default to tag=version-1
		verrel=${1#*=}
		force_rel=${verrel##*-}
		force_ver=${verrel%-*}
		shift ;;
	    --fuzz=* )
		# patch application fuzz
		FUZZ="--fuzz=${1#*=}"
		shift ;;
	    --use-all-packaging )
		USE_ALL_PKG=true
		shift ;;
	    * )
		echo "Error $1 not recognised"
		exit 1;;
	esac
    done

    [[ $basetag ]] || { echo "tag not supplied"; exit 1; }
    [[ $pkgdir ]] || { echo "pkgdir not supplied"; exit 1; }

    [[ $gp_type == "pristine-tar" && ! $pbranch ]] && {
	echo "Error: pristine-tar requires a --patch-branch value"; exit 1; }

    # Determine version/release numbers
    #get_verrel_from_packaging($pkgdir)
    rel=${rel:-$force_rel}
    ver=${ver:-$force_ver}

    src_tag=$DISTRO-${ver}
    patches_tag=$DISTRO-${ver}-${rel}
    pkg_tag=pkg-$DISTRO-${ver}-${rel}

    [[ $gp_type == "pristine-tar" && ! $pbranch ]] && {
	echo "Error: pristine-tar requires a --patch-branch value"; exit 1; }

    pbranch="${DISTRO}-${ver}"

    if ! [[ -d .git ]]; then
	echo "This is not a git repository"
	exit 1
    fi

    # Verify there's only a single spec or yaml file.
    numspec=$(ls $pkgdir/*spec 2>/dev/null | wc -l)
    numyaml=$(ls $pkgdir/*yaml 2>/dev/null | wc -l)
    if [[ $numspec -gt 1 ]] || [[ $numyaml -gt 1 ]]; then
	echo "gp_setup doesn't support packaging with >1 .spec or .yaml file"
	exit 1
    fi

    # ... and record it
    specfile=$(cd $pkgdir; ls *.spec 2>/dev/null)
    yamlfile=$(cd $pkgdir; ls *.yaml 2>/dev/null)

    # Guess the tarball
    tarball=$(cd $pkgdir; find * -name *t*gz)
    [[ ! $tarball ]] && tarball=$(cd $pkgdir; find * -name *t*bz2)
    echo "tarball: $tarball"

    # If this is a pure pristine-tar with no git tree then just unpack
    # the tarball as a starting point
    if [[ $gp_type == "pristine-tar" && $unpack ]] ; then
	echo "Pristine tar : Unpacking tarball as initial commit"
	unpack_tarball $pkgdir/$tarball	
	git add .
	git commit -m"Initial commit from $tarball"
	# Create a tag for the tarball - it's OK to do it now in unpack mode
	git tag $basetag
    fi

    # Branch from the appropriate tag
    git checkout  -q -f $basetag
    src_tag_sha1=$(git show-ref -s HEAD) # Store this sha1 so we make tags later

    [[ $pbranch ]] && git checkout -b $pbranch # Make a patches branch if we need to

    # Pristine tar approach needs some extra work
    # 1. Commit the tarball in packaging to pristine tar
    # 2. Replace the checked-out tree with the tarball
    # 3. Commit any deltas (empty if needed)
    # 4. Ready for patches
    if [[ $gp_type == "pristine-tar" ]] ; then
	echo "Pristine tar : removing all files and unpacking tarball to record any delta to $basetag"
	pristine-tar commit $pkgdir/$tarball $basetag
	unpack_tarball $pkgdir/$tarball	
	git add .; git ls-files --deleted | xargs --no-run-if-empty git rm
	git commit --allow-empty -m"pristine-tar-delta: Import any changes from the released tarball into the Mer source tree ready for local patches"
    fi

    # Apply the patches mentioned in the spec file in the order they appear
    # We'll probably need a --fuzz option at some point
    # Keep the dir clean and we should abort/warn when patches don't apply
    for patch in $(cd $pkgdir; grep Patch.*: *spec | cut -f2 -d:); do
	if [[ ! $pbranch ]] ; then echo "Error: No patch-tag supplied and patches found"; exit 1; fi
	
	echo Applying $patch
	if ! patch $FUZZ -p1 --no-backup-if-mismatch -s < $pkgdir/$patch; then
	    echo "Patch $pkgdir/$patch seemed to apply badly - fixup in a different terminal and press return to commit it and continue"
	    read dummy
	fi
	git commit -am"$(basename $patch .patch)"
	have_patches=1
    done

    # Only do this next section if we actually found patches to apply
    if [[ $have_patches ]] ; then
	# We need to tag the patch branch head
	patches_tag_sha1=$(git show-ref -s HEAD)

        # Pristine tar needs to skip the pristine-tar-delta patch
	if [[ $gp_type == "pristine-tar" ]] ; then
	    tag1="${pbranch}~$(($(count_commits $basetag $pbranch ) - 1))"
	else
	    tag1=$src_tag
	fi

        # We now have all we need to create the _src file
	_src="$gp_type:$tarball:$src_tag:$patches_tag"
    else
	# No patches variant of _src
	_src="$gp_type:$tarball:$src_tag"
    fi

    prepare_pkg_branch --quiet

    # Copy all the packaging files in (assuming no hidden files)
    cp $pkgdir/* .
    # Clean up the tarball we found and any patches which are now autogenerated
    # Allow --use-all-packaging to override complex cases
    if [[ ! $USE_ALL_PKG ]] ; then
	rm -f *t*gz *t*bz2
	rm -f *patch
	echo "cleaned up"
	ls -laF
    fi

    # Provide patch information for yaml/spec
    if [[ -e $yamlfile ]]; then
	if [[ $gp_type != "pristine-tar" ]] ; then
	    echo "SetupOptions: -q -n src"  >> $yamlfile
	fi
	gp_mkpkg --no-checkout --no-tarball

	specify -N $yamlfile
    else
	if [[ $gp_type == "pristine-tar" ]] ; then
	    gp_mkpkg -n --no-tarball  --no-src
	else
	    gp_mkpkg -n --no-tarball
	fi
    fi

    # Everything else is normal packaging
    git add * >/dev/null 2>&1

    # And finally a commit
    git commit -m"Initial git package of $basetag as $pbranch"

    git tag $src_tag $src_tag_sha1
    [[ $patches_tag_sha1 ]] && git tag $patches_tag $patches_tag_sha1
    git tag $pkg_tag

    # Comment on what we've created
    echo Guessed 
    cat _src
    echo for _src

    # and a reminder not to bitch *too* much
    echo "gp_setup --existing isn't thoroughly tested - please fix and/or report any bugs you find"
}

usage_pkg(){
cat <<EOF
    --pkg
          Used in an existing git repo this creates a pkg branch
          called pkg-$DISTRO with a suitable .gitignore and a _src
          file.
          The user must then add packaging files.
EOF

}

prepare_pkg_branch() {
    # Verify there's no packaging branch already
    if git show-ref --verify --quiet refs/heads/${pkg_branch}; then
	echo "${pkg_branch} branch exists already"
	exit 1
    fi

    require_clean_work_tree

    # This creates the orphaned pkg-* branch
    git checkout --orphan ${pkg_branch}
    git rm -q -rf .

    # Remove stray files that may have crept in but only if we're in a .git repo
    if [[ -d .git ]] ; then
	find . -mindepth 1 -maxdepth 1 -not -name .git -print0 | xargs -0 rm -rf
    fi

    # We typically expect to be used in OBS/osc projects
    echo .osc > .gitignore
    echo ${_src:-git:pkg.tar.bz2:srctag[:patchestag]} > _src

    git add _src .gitignore

    # If invoked internally then we 
    [[ $1 == "--quiet" ]] && return

    cat <<EOF
Now on ${pkg_branch} branch with _src and .gitignore.

You should create suitable packaging on this branch.

See https://wiki.merproject.org/wiki/Git_pkg for more help.

EOF

}

case $1 in
    --existing )
	shift
	use_existing $* ;;

    --pkg* )
	tag=${1#*=}
	prepare_pkg_branch ;;

    * )
	usage ;;
esac
