#!/usr/bin/perl -w

use strict;

my $setup_src = (defined $ARGV[0] and $ARGV[0] eq "--setup_src") ? 1 : 0;


# Skip to the SourceXX: line
while (<STDIN>) {
  print unless /^Patch/;
  next unless /^Source/;
  last;
}
# Now print all Source lines but not Patch lines
while (<STDIN>) {
  next if /^Patch/;
  if (/^Source/) { print; next; }
  last; # Leaving with $_ needing printing
}
my $unprinted = $_;

# Insert our set of Patches if there are any:
open(PatchFile, ".gp/spec-Patch") and print <PatchFile>;

print $unprinted;
# Skip to %prep
while (<STDIN>) {
  print unless /^Patch/ ;
  last if /^%prep/;
}
my $maybe_setup = <STDIN>;
if ($maybe_setup !~ /^%setup/) {
  print STDERR "No %setup following %prep - %patch macros are almost certainly wrong\n";
} elsif ( $setup_src == 1 ) {
  print STDERR "Adjusting %setup since git-pkg unpacks to src/\n";
  print "# Adjusting %%setup since git-pkg unpacks to src/\n";
  $maybe_setup =~ s/-n [^ ]*$/-n src/;
}
print "$maybe_setup\n";
open(patchFile, ".gp/spec-patch") and print <patchFile>;
while (<STDIN>) {
  print unless /^%patch/ ;
}

